name: .NET Core CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Package NuGets
    env:
      NUPKG_MAJOR: 0.999
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Setup NuGet 5.x
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Setup MAUI
        shell: pwsh
        run: |
          & dotnet workload install maui ios android maccatalyst

      - name: Build
        run: dotnet build --configuration Release

      # - name: Test
      #   run: dotnet test --configuration Release

      - name: Package NuGets
        shell: pwsh
        run: |
          $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
          echo "PACKAGE VERSION: $VERSION"

          New-Item -ItemType Directory -Force -Path .\artifacts

          dotnet pack --output ./artifacts --configuration Release -p:PackageVersion=$VERSION ./ZXing.Net.MAUI/ZXing.Net.MAUI.csproj
          dotnet pack --output ./artifacts --configuration Release -p:PackageVersion=$VERSION ./ZXing.Net.MAUI.Controls/ZXing.Net.MAUI.Controls.csproj
          dotnet pack --output ./artifacts --configuration Release -p:PackageVersion=$VERSION ./ZXing.Net.MAUI.Comet/ZXing.Net.MAUI.Comet.csproj

      - name: Upload NuGet Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zxing-nugets
          path: ./artifacts
